### PR TITLE
Fix pressing `Enter` while searching also triggering navigation back on physical keyboards

### LINKED ISSUE #1131: Physical Keyboard issue
### Steps to reproduce

- open Global Search or Browse Search
- type something
- press enter to trigger search

### Expected behavior

search

### Actual behavior

automatically selects the back button and exits out of the screen (even tho search was successfully triggered)

### Crash logs

_No response_

### Mihon version

r6808 and 0.16.5

### Android version

Android 11

### Device

Waydroid

### Other details

- this is possibly an issue with compose, since it works as expected on non-compose forks (like yokai)
- not dependent on waydroid, as can be reproduced with actual phone and keyboard
- really painful during ext development/testing 😔

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
On a physical/hardware keyboard, a keystroke sends two events. One of key press and one on key release, so effectively two events on a single keystroke. ([ref](https://developer.android.com/develop/ui/compose/touch-input/keyboard-input/commands#key_events))
This caused `searchAndClearFocus` in `SearchToolbar` composable to trigger twice, second time tapping the back button and exiting out of search.
To fix this, I have changed it to only trigger on Key release, which is the behavior of software keyboard when tapping the enter/search key.

Also changed it so focus is moved next, and not to the back button

Note: only tested on Waydroid, I don't know if this will have any other side effects on other devices with keyboards

closes #1131

### CODE REVIEW

File: presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt [hunk 1]
```diff
@@ -53,8 +55,17 @@ fun Modifier.clickableNoIndication(
...
     when (it.key) {
         Key.Enter, Key.NumPadEnter -> {
-            action()
-            true
+            // Physical keyboards generate two event types:
+            // - KeyDown when the key is pressed
+            // - KeyUp when the key is released
+            // To match the behavior of software keyboards (IME),
+            // trigger [action] only on the KeyUp event.
+            if (it.type == KeyEventType.KeyUp) {
```
Comment (AntsyLich) [inline presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt:63]: But we're working with physical keyboard here where stuff usually triggers on `KeyDown`

File: CHANGELOG.md [hunk 2]
```diff
@@ -51,6 +51,7 @@ The format is a modified version of [Keep a Changelog](https://keepachangelog.co
 - Fix empty layout not appearing in browse source screen in some cases ([@NarwhalHorns](https://github.com/NarwhalHorns)) ([#2043](https://github.com/mihonapp/mihon/pull/2043))
 - Fix Pill not following the local text style ([@AntsyLich](https://github.com/AntsyLich)) ([`f8cb506`](https://github.com/mihonapp/mihon/commit/f8cb506))
 - Fix downloader stopping after failing to create download directory of a manga ([@AntsyLich](https://github.com/AntsyLich)) ([#2068](https://github.com/mihonapp/mihon/pull/2068))
+- Fix enter key exiting out of search on physical keyboards ([@AwkwardPeak7](https://github.com/AwkwardPeak7)) ([#2077](https://github.com/mihonapp/mihon/pull/2077))
```
Comment (AntsyLich) [inline CHANGELOG.md:54]:
```suggestion
- Fix pressing `Enter` while searching also triggering navigation back on physical keyboards ([@AwkwardPeak7](https://github.com/AwkwardPeak7)) ([#2077](https://github.com/mihonapp/mihon/pull/2077))
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

File: presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt (hunk 1 above)
Comment (AwkwardPeak7) [reply presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt:63]: shouldn't the behavior be uniform across software and physical keyboard?

**Review by AntsyLich — APPROVED** [review]
