### PR TITLE
Fix new extension install not registering in app.

### LINKED ISSUE #246: Installed new extensions do not appear after installation, but appear after restarting the application.
### Steps to reproduce

1. Download new extension 
3. Install new extension

### Expected behavior

When installing the extension it does not appear installed, but only after restarting the application.

### Actual behavior

When installing the extension it does not appear installed, but only after restarting the application.

### Crash logs

_No response_

### Mihon version

0.16.2

### Android version

Android 12

### Device

Tecno Spark 10c

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #246

The problem mainly was that `_untrustedExtensionsFlow` wasn't updated with the new extension due to early return.

~But fixing that caused crashes due to duplicate key in LazyColumn. workaround for this was to remove duplicates for installed + untrusted extensions in `ExtensionsScreenModel`.~

~Now there is another bug, after updating and trusting an extension, it shows up two times. idk how to fix this~

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt [hunk 1]
```diff
@@ -340,9 +340,12 @@ class ExtensionManager(
...
                 .find { it.pkgName == extension.pkgName }
-                ?: return
-            _installedExtensionsFlow.value -= installedExtension
-            _untrustedExtensionsFlow.value += extension
+
+            if (installedExtension != null) {
+                _installedExtensionsFlow.value -= installedExtension
+            } else {
+                _untrustedExtensionsFlow.value += extension
+            }
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt:348]: The extension won't appear as untrusted after updating 🤔

Comment (AwkwardPeak7) [reply app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt:348]: it does show up
