### PR TITLE
Apply "Downloaded only" filter to non library entries as well

### LINKED ISSUE #1593: "Downloaded only" mode causes chapters in non-Library entries to error
### Steps to reproduce

1. Enable "Downloaded only" mode in Mihon More Page
2. Go into any source to browse/find/read chapters in (not in Library) entries
3. Clicking on any chapter will give "Collection contains no element matching the predicate" error

### Expected behavior

Should give a reminder or something to disable "Downloaded only" mode, or adjust it so it doesn't affect non-Library entries

### Actual behavior

Throws the "Collection contains no element matching the predicate" error

### Crash logs

_No response_

### Mihon version

0.17.1

### Android version

Android 14

### Device

Samsung Z Fold 6

### Other details

Previously reported in #530 but was closed as unclear/unreproducible issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
Closes #1593

### CODE REVIEW

File: app/src/main/java/eu/kanade/domain/manga/model/Manga.kt [hunk 1]
```diff
@@ -35,7 +35,7 @@ fun Manga.chaptersFiltered(): Boolean {
         bookmarkedFilter != TriState.DISABLED
 }
 fun Manga.forceDownloaded(): Boolean {
-    return favorite && Injekt.get<BasePreferences>().downloadedOnly().get()
+    return Injekt.get<BasePreferences>().downloadedOnly().get()
 }
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/domain/manga/model/Manga.kt:39]: No point on keeping this as a function then

File: app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt [hunk 2]
```diff
@@ -97,7 +99,7 @@ fun ChapterSettingsDialog(
                     FilterPage(
                         downloadFilter = manga?.downloadedFilter ?: TriState.DISABLED,
                         onDownloadFilterChanged = onDownloadFilterChanged
-                            .takeUnless { manga?.forceDownloaded() == true },
+                            .takeUnless { Injekt.get<BasePreferences>().downloadedOnly().get() == true },
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt:102]: Add this at the root of `ChapterSettingsDialog`
```kt
val downloadOnly = remember { Injekt.get<BasePreferences>().downloadedOnly().get() }
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]
And changelog

File: app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt [hunk 3]
```diff
@@ -97,7 +102,7 @@ fun ChapterSettingsDialog(
                     FilterPage(
                         downloadFilter = manga?.downloadedFilter ?: TriState.DISABLED,
                         onDownloadFilterChanged = onDownloadFilterChanged
-                            .takeUnless { manga?.forceDownloaded() == true },
+                            .takeUnless { downloadedOnly == true },
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt:105]:
```suggestion
                            .takeUnless { downloadedOnly },
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

**Review by AntsyLich — APPROVED** [review]
