### PR TITLE
Fix one-part tall image recompression

### LINKED ISSUE #3117: Split tall images just bloat image without actuall splitting
### Steps to reproduce

Download chapter with and without "split tall images".
https://mangafire.to/read/my-chubby-princesss.29914/en/chapter-1

### Expected behavior

Split tall images, leave regular ones.

### Actual behavior

Mihon "splits" image when it shouldn't have and bloat it size.
Example: first image of chapter from above.
When "Split tall image" is disabled it download just a original file:

Image
<br><br>
But when you enable "split tall image" it "splits" image without splitting and just bloat it size:

Image
<br><br>
Image stays the same in term of dimensions (1024x4385px), and first image has only one part after "splitting", but it size almost twice of the original.

### Crash logs

_No response_

### Mihon version

0.19.5

### Android version

Android 9

### Device

Nokia 8

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.19.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Mihon does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

### PR DESCRIPTION
**Pull request by leodyversemilla07**
## Summary
- use the actual split-count calculation when deciding whether to split a tall image
- skip rewriting downloaded images when the computed split result would only produce a single part
- add regression coverage for the one-part boundary case behind the report

## Issue
- Fixes #3117

## Testing
- ./gradlew spotlessCheck
- ./gradlew assembleRelease -Pinclude-telemetry -Penable-updater
- ./gradlew testReleaseUnitTest

## Self-review
- checked that the fix only changes the one-part split path and does not change how real multi-part splits are written
- verified the new helper keeps the split decision and split-count math in one place
- no visual changes

### CODE REVIEW

File: core/common/src/main/kotlin/tachiyomi/core/common/util/system/TallImageSplitCalculator.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
+package tachiyomi.core.common.util.system
+
+internal object TallImageSplitCalculator {
+
+    fun calculatePartCount(imageHeight: Int, optimalImageHeight: Int): Int {
+        require(imageHeight > 0) { "imageHeight must be positive" }
+        require(optimalImageHeight > 0) { "optimalImageHeight must be positive" }
+        return (imageHeight - 1) / optimalImageHeight + 1
```
Comment (AntsyLich) [inline core/common/src/main/kotlin/tachiyomi/core/common/util/system/TallImageSplitCalculator.kt:9]:
```suggestion
        // -1 so it doesn't try to split when imageHeight = optimalImageHeight
        return (imageHeight - 1) / optimalImageHeight + 1
```

File: core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt [hunk 2]
```diff
@@ -226,8 +230,10 @@ object ImageUtil {
         val options = extractImageOptions(imageSource).apply {
             inJustDecodeBounds = false
         }
-
         val splitDataList = options.splitData
+        if (splitDataList.size <= 1) {
+            return true
+        }
```
Comment (AntsyLich) [inline core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt]: Isn't this redundant due to the `isTallImage` check above?

**Review by leodyversemilla07 — COMMENTED** [review]
Thanks for the review! I've addressed both comments:

1. Added the explanatory comment for the split calculation formula
2. Removed the redundant splitDataList size check as you suggested - the isTallImage check already guarantees the split count will be > 1

**Comment by AntsyLich** [comment]
rebase and add a changelog entry

File: core/common/src/main/kotlin/tachiyomi/core/common/util/system/TallImageSplitCalculator.kt [hunk 3]
```diff
@@ -0,0 +1,18 @@
+package tachiyomi.core.common.util.system
+
+internal object TallImageSplitCalculator {
+
+    fun calculatePartCount(imageHeight: Int, optimalImageHeight: Int): Int {
+        require(imageHeight > 0) { "imageHeight must be positive" }
+        require(optimalImageHeight > 0) { "optimalImageHeight must be positive" }
+        // -1 so it doesn't try to split when imageHeight = optimalImageHeight
+        // -1 so it doesn't try to split when imageHeight = optimalImageHeight
```
Comment (AntsyLich) [inline core/common/src/main/kotlin/tachiyomi/core/common/util/system/TallImageSplitCalculator.kt]:
```suggestion
        // -1 so it doesn't try to split when imageHeight = optimalImageHeight
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 4]
```diff
@@ -17,6 +17,9 @@ The format is a modified version of [Keep a Changelog](https://keepachangelog.co
 ### Improved
 - Show informative error when trying to add unapproved titles to list on MAL ([@MajorTanya](https://github.com/MajorTanya)) ([#3155](https://github.com/mihonapp/mihon/pull/3155))
 
+### Fixed
+- Fix one-part tall image recompression ([@leodyversemilla07](https://github.com/leodyversemilla07)) ([#3121](https://github.com/mihonapp/mihon/pull/3121))
```
Comment (AntsyLich) [inline CHANGELOG.md]:
```suggestion
- Fix app trying to split long strip when not needed ([@leodyversemilla07](https://github.com/leodyversemilla07)) ([#3121](https://github.com/mihonapp/mihon/pull/3121))
```
