### PR TITLE
Cloudflare X-Requested-With leak fix due chromium project changes

### LINKED ISSUE #2426: [Detection] Hide Mihon in WebView
### Describe your suggested feature

When inside a WebView, Mihon is advertised itself as `app.mihon` in the `x-request-with` header. 
It is also advertised as `WebView` in the ua hints.

### Other details

```json
{
  "http_version": "h2",
  "method": "GET",
  "user_agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36",
  "http2": {
    "akamai_fingerprint": "1:65536;2:0;4:6291456;6:262144|15663105|0|m,a,s,p",
    "akamai_fingerprint_hash": "52d84b11737d980aef856699f885ca86",
    "sent_frames": [
      [...],
      {
        "frame_type": "HEADERS",
        [...]
        "headers": [
          ":method: GET",
          ":authority: tls.peet.ws",
          ":scheme: https",
          ":path: /api/all",
          "sec-ch-ua: \\\"Not;A=Brand\\\";v=\\\"99\\\", \\\"Android WebView\\\";v=\\\"139\\\", \\\"Chromium\\\";v=\\\"139\\",
          [...]
          "x-requested-with: app.mihon",
          [...]
        ],
      }
    ]
  }
}
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Guzmazow**
Closes #2426 
WebView started leaking X-Requested-With header due to Chromium update and CloudFlare started blocking all requests

Cause:
Chromium project renamed BuildInfo to ApkInfo
https://github.com/chromium/chromium/commit/a0fc35030eb7d3623d5dce9bb990be369d59fb2f

### CODE REVIEW

**Comment by MajorTanya** [comment]
I believe there's an issue or a PR about this already, let me check

Edit: #2426

File: app/src/main/java/eu/kanade/tachiyomi/App.kt [hunk 1]
```diff
@@ -220,8 +220,8 @@ class App : Application(), DefaultLifecycleObserver, SingletonImageLoader.Factor
             // Override the value passed as X-Requested-With in WebView requests
             val stackTrace = Looper.getMainLooper().thread.stackTrace
             val isChromiumCall = stackTrace.any { trace ->
-                trace.className.equals("org.chromium.base.BuildInfo", ignoreCase = true) &&
-                    setOf("getAll", "getPackageName", "<init>").any { trace.methodName.equals(it, ignoreCase = true) }
+                setOf("org.chromium.base.BuildInfo", "org.chromium.base.ApkInfo").any { trace.className.equals(it, ignoreCase = true) } &&
+                setOf("getAll", "getPackageName", "<init>").any { trace.methodName.equals(it, ignoreCase = true) }
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/App.kt]: Looking at the code `ApkInfo` should only have an associated `<init>` call. We can probably simplify this a bit based on that. It's still fine as is. Also add a entry in CHANGELOG.md

Comment (AwkwardPeak7) [reply app/src/main/java/eu/kanade/tachiyomi/App.kt]: Imo it should not be simplified so that varying versions of WebView across different Android versions work correctly.

Comment (Guzmazow) [reply app/src/main/java/eu/kanade/tachiyomi/App.kt]: Added changelog entry

**Comment by arispati** [comment]
I can't bypass Cloudflare and it always returns to the Cloudflare verification page.
Is this PR related to the issue I'm experiencing or is it a different issue?

**Comment by Guzmazow** [comment]
Yes, I had exactly the same effect before I patched this.

> I can't bypass Cloudflare and it always returns to the Cloudflare verification page.
> Is this PR related to the issue I'm experiencing or is it a different issue?

File: app/src/main/java/eu/kanade/tachiyomi/App.kt [hunk 2]
```diff
@@ -220,8 +220,12 @@ class App : Application(), DefaultLifecycleObserver, SingletonImageLoader.Factor
...
             val stackTrace = Looper.getMainLooper().thread.stackTrace
             val isChromiumCall = stackTrace.any { trace ->
-                trace.className.equals("org.chromium.base.BuildInfo", ignoreCase = true) &&
-                    setOf("getAll", "getPackageName", "<init>").any { trace.methodName.equals(it, ignoreCase = true) }
+                setOf("org.chromium.base.BuildInfo", "org.chromium.base.ApkInfo").any {
+                    trace.className.equals(it, ignoreCase = true)
+                } &&
+                    setOf("getAll", "getPackageName", "<init>").any {
+                        trace.methodName.equals(it, ignoreCase = true)
+                    }
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/App.kt]:
```suggestion
                tracke.className.lowercase() in setOf("org.chromium.base.buildinfo", "org.chromium.base.apkinfo") &&
                    trace.methodName.lowercase() in setOf("getall", "getpackagename", "<init>")
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -15,6 +15,7 @@ The format is a modified version of [Keep a Changelog](https://keepachangelog.co
 - Fix height of description not being calculated correctly if images are present ([@Secozzi](https://github.com/Secozzi)) ([#2382](https://github.com/mihonapp/mihon/pull/2382))
 - Fix migration progress not updating after manual search ([@Secozzi](https://github.com/Secozzi)) ([#2484](https://github.com/mihonapp/mihon/pull/2484))
 - Fix category migration flag being ignored due to incorrect check against chapter flag ([@Secozzi](https://github.com/Secozzi)) ([#2484](https://github.com/mihonapp/mihon/pull/2484))
+- Fix hiding package name in WebView ([@Guzmazow](https://github.com/Guzmazow)) ([#2491](https://github.com/mihonapp/mihon/pull/2491))
```
Comment (AntsyLich) [inline CHANGELOG.md]:
```md
### Improved 
- Spoofing of `X-Requested-With` header to support newer WebView versions
```

And should go above fixes

**Review by AntsyLich — CHANGES_REQUESTED** [review]

**Comment by Guzmazow** [comment]
If anyone wants this without the new mihon version release they can just "uninstall updates" of Android WebView.

File: app/src/main/java/eu/kanade/tachiyomi/App.kt (hunk 2 above)
Comment (Guzmazow) [reply app/src/main/java/eu/kanade/tachiyomi/App.kt]: i am afraid the spotless check will start splitting this into rows...
but i will try it later

**Comment by MajorTanya** [comment]
> If anyone wants this without the new mihon version release they can just "uninstall updates" of Android WebView.

Bad advice is worse than no advice. This would send most people back dozens of versions which can come with way more problems than it could ever fix.

File: CHANGELOG.md (hunk 3 above)
Comment (Guzmazow) [reply CHANGELOG.md]: done

File: app/src/main/java/eu/kanade/tachiyomi/App.kt (hunk 2 above)
Comment (Guzmazow) [reply app/src/main/java/eu/kanade/tachiyomi/App.kt]: done

**Review by AntsyLich — APPROVED** [review]
