### PR TITLE
Refresh Trackers Before Overwriting Remote

### LINKED ISSUE #1522: Redundant tracking snackbar when chapter matches tracking
### Steps to reproduce

Have the "Update progress after reading" setting enabled and "Update progress when marking as read" to "Always ask":
1. Read chapter X (trackers are now on X)
2. Select chapter X+1
3. Hit "Mark previous as read" to clean up partial stragglers (X.y, X.z ...)

### Expected behavior

4. Tracking checks that every tracker's progress is >= last chapter marked as read (rounded as integer) before prompting to update

### Actual behavior

4. Previous chapters are marked as read but there's a snackbar prompting to update tracking to chapter X, which they already are

### Crash logs

Not a Crash

### Mihon version

SY Preview r574 (based on Mihon 0.17)

### Android version

13

### Device

Chinatablet

### Other details

image

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1793: Tracker updates wrong chapter.
### Steps to reproduce

1) Change tracker's chapter number outside Mihon app.
2) Mark unread chapter as read / manually read chapter.
3) Chapter is updated to the chapter.

### Expected behavior

1) Mark the chapter as read.
2) Check what is the chapter number on the tracker.
3) If the marked number is higher than the tracker number, then update.
Eg: On tracker x entry has 24 chapters read & you marked chapter 12 then it should not update the tracker.

### Actual behavior

It doesn't check for what is the chapter number on the tracker, it updates it even if the tracker's chapter is higher than the marked chapter.

### Crash logs

_No response_

### Mihon version

r7113

### Android version

Android 16

### Device

Google Pixel 6A

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Animeboynz**
Fixes #1793 
Fixes #1522 
https://github.com/mihonapp/mihon/issues/1522 was basically fixed already but his should make sure that it doesn't happen

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt [hunk 1]
```diff
@@ -767,6 +772,27 @@ class MangaScreenModel(
         }
     }
 
+    private suspend fun refreshTrackers() {
+        val refreshTracks = Injekt.get<RefreshTracks>()
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt:776]: Put this in constructor

Comment (Animeboynz) [reply app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt:776]: Should I change it here too?
https://github.com/mihonapp/mihon/blob/d7a1ae27346a983f658fb88cb525cf8b785b3bb3/app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt#L229-L249

**Comment by AntsyLich** [comment]
Changelog?

**Review by AntsyLich — APPROVED** [review]
