### PR TITLE
Fix next chapter button not changing chapter

### LINKED ISSUE #875: Jump to chapter issues
### Steps to reproduce

I use the comic reading method, and when I am reading, when I jump to the next chapter, sometimes I may only jump to the last section of the chapter I am reading, and manually swipe down to actually get to the next chapter.Is this a mispositioning?

### Expected behavior

Normally, when you jump to the next chapter, you will jump to the first summary of the next chapter, which is the first picture of the next chapter, rather than the last sentence of the chapter you are currently reading.

### Actual behavior

In fact, this happens quite often, often jumping to the last image of the current chapter, and the table of contents in the upper left corner of the reading page shows that it is also the current chapter instead of the next chapter. Of course, the progress bar in the middle of the reader screen is the same.

### Crash logs

_No response_

### Mihon version

0.16.5

### Android version

Android13

### Device

Redmi 11T pro

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by perokhe**
Adapted from TachiyomiSY

Closes #875

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt [hunk 1]
```diff
@@ -125,6 +125,14 @@ class PagerViewerAdapter(private val viewer: PagerViewer) : ViewPagerAdapter() {
...
             viewer.moveToPage(insertPageLastPage!!)
         }
+
+        // Move to first page of the new chapter if the current page is not on the same chapter
+        val currPage = items.getOrNull(viewer.pager.currentItem)
+        if (currPage is ReaderPage && currPage.chapter != currentChapter && currPages != null) {
+            val firstPage = currPages.minBy { it.index }
+            val index = items.indexOf(firstPage)
+            viewer.pager.setCurrentItem(index, false)
+        }
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt:135]: Why is this necessary?

Comment (perokhe) [reply app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt:135]: I forgot that part wasn't needed anymore after removing the listener. I'll delete it

**Comment by AntsyLich** [comment]
Add a change log entry

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,7 @@ The format is a modified version of [Keep a Changelog](https://keepachangelog.co
 ## [Unreleased]
 ### Fixes
 - Fix Bangumi search results including novels ([@MajorTanya](https://github.com/MajorTanya)) ([#1885](https://github.com/mihonapp/mihon/pull/1885))
+- Fix next chapter button not changing chapter ([@perokhe](https://github.com/perokhe)) ([#1920](https://github.com/mihonapp/mihon/pull/1920))
```
Comment (AntsyLich) [inline CHANGELOG.md:16]:
```suggestion
- Fix next chapter button occasionally jumping to the last page of the current chapter ([@perokhe](https://github.com/perokhe)) ([#1920](https://github.com/mihonapp/mihon/pull/1920))
```

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt [hunk 3]
```diff
@@ -275,6 +275,10 @@ abstract class PagerViewer(val activity: ReaderActivity) : Viewer {
      * Sets the active [chapters] on this pager.
      */
     private fun setChaptersInternal(chapters: ViewerChapters) {
+        // Remove listener since we're about to change the size of the items
+        // If we don't, the size change could put us on a new chapter
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt:279]:
```suggestion
        // Remove listener so the change in item doesn't trigger it
```

**Review by AntsyLich — APPROVED** [review]

**Comment by AntsyLich** [comment]
When you open a chapter for the first time the page number doesn't appear anymore unless you change to a different page
