### PR TITLE
Spoof or remove `X-Requested-With` header from webview

### LINKED ISSUE #1659: WebView: X-Requested-With sends the app package name to the host
### Steps to reproduce

- Add a proxy to your Android device;
- Open the web view and see the headers

### Expected behavior

Remove the **X-Requested-With**

### Actual behavior

X-Requested-With is configured

### Crash logs

_No response_

### Mihon version

0.17.1

### Android version

Android 13

### Device

POCO F3

### Other details

The web view sends the ID of the embedded browser, which is different from a request from a regular browser.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
- fix the webview detection in `getPackageName` to correctly detect it and return a spoofed package (thanks to @vetleledaal)
- spoofed package will be `com.android.chrome` (google chrome) or in some cases when it isn't installed, `com.android.settings`
  - this needs to be a valid installed package, otherwise the app crashes 
- override `shouldInterceptRequest` of the webview to use okhttp for making the calls and being able to remove the header completely
  - this isn't called for post or xhr/fetch calls in js so spoofed package name is needed 

closes #1659

### CODE REVIEW

File: core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/WebViewUtil.kt [hunk 1]
```diff
@@ -53,6 +51,18 @@ object WebViewUtil {
 
         return context.packageManager.hasSystemFeature(PackageManager.FEATURE_WEBVIEW)
     }
+
+    fun spoofedPackageName(context: Context): String {
+        val chromePkg = "com.android.chrome"
```
Comment (AntsyLich) [inline core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/WebViewUtil.kt:56]: make this and the settings one private static val

File: core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkHelper.kt [hunk 2]
```diff
@@ -60,11 +56,18 @@ class NetworkHelper(
             PREF_DOH_CONTROLD -> builder.dohControlD()
             PREF_DOH_NJALLA -> builder.dohNajalla()
             PREF_DOH_SHECAN -> builder.dohShecan()
+            else -> builder
         }
-
-        builder.build()
     }
 
+    val noCfClient = clientBuilder.build()
```
Comment (AntsyLich) [inline core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkHelper.kt:63]:
```suggestion
    val nonCloudflareClient = clientBuilder.build()
```

File: app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt [hunk 3]
```diff
@@ -60,6 +67,9 @@ fun WebViewScreenContent(
     val navigator = rememberWebViewNavigator()
     val uriHandler = LocalUriHandler.current
     val scope = rememberCoroutineScope()
+    val context = LocalContext.current
+    val network = Injekt.get<NetworkHelper>()
+    val spoofedPackageName = WebViewUtil.spoofedPackageName(context)
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt:72]:
```suggestion
    val context = LocalContext.current
    val uriHandler = LocalUriHandler.current
    val scope = rememberCoroutineScope()
    val network = remember { Injekt.get<NetworkHelper>() }
    val spoofedPackageName = remember { WebViewUtil.spoofedPackageName(context) }
```

File: app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt [hunk 4]
```diff
@@ -114,6 +124,42 @@ fun WebViewScreenContent(
...
+                                if (key == "X-Requested-With" &&
+                                    value in setOf(context.packageName, spoofedPackageName)
+                                ) {
+                                    return@forEach
+                                }
+                                addHeader(key, value)
+                            }
+                            method(request.method, null)
+                        }.build(),
+                    ).execute()
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt:146]:
```suggestion
                    val internalRequest = Request.Builder().apply { 
                        url(request!!.url.toString())
                        method(request.method, null)

                        request.requestHeaders.forEach { (key, value) ->
                            if (key == "X-Requested-With" && value in setOf(context.packageName, spoofedPackageName)) {
                                return@forEach
                            }
                            addHeader(key, value)
                        }
                        
                    }
                        .build()
                    val response = network.nonCloudflareClient.newCall(internalRequest).execute()
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

**Review by AntsyLich — APPROVED** [review]
