### PR TITLE
Stop tap zones from triggering when scrolling is stopped by tapping

### LINKED ISSUE #2671: Reader: Tap zone/touch input in long-strip while scrolling issue
### Steps to reproduce

1. While scrolling in Long-strip reading mode, tap to stop at current position
2. Mihon interprets the tap as either a tap zone interaction and/or brings up the reader overlay

### Expected behavior

Tapping the screen while scrolling should stop at the current chapter page position

### Actual behavior

It scrolls and/or brings up the reader overlay while trying to read.

(From #1742) Here's the current behavior: https://youtu.be/-ig3eZtqi58

### Crash logs

_No response_

### Mihon version

0.19.3

### Android version

N/A

### Device

N/A

### Other details

Catch-all request for the prior issue request (resolved #1742) around reader overlay interaction behavior & tap zones scrolling, due to (0.19.3) #2670 reverting (0.19.2) #2518 & merged #2650.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Mihon does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
Closes #2671

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt [hunk 1]
```diff
@@ -52,6 +52,9 @@ class WebtoonRecyclerView @JvmOverloads constructor(
     var tapListener: ((MotionEvent) -> Unit)? = null
     var longTapListener: ((MotionEvent) -> Boolean)? = null
 
+    private var animatingFling = false
+    private var tapDuringFling = false
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt]:
```suggestion
    private var isManuallyScrolling = false
    private var tapDuringManualScroll = false
```

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt [hunk 2]
```diff
@@ -212,10 +223,16 @@ class WebtoonRecyclerView @JvmOverloads constructor(
         }
     }
 
+    fun setAnimatingFling() {
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt]:
```suggestion
    fun onManualScroll() {
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -10,6 +10,10 @@ The format is a modified version of [Keep a Changelog](https://keepachangelog.co
 - `Fixed` - for any bug fixes.
 - `Other` - for technical stuff.
 
+## [Unreleased]
+### Fixed
+- Fix reader tap zones triggering after scrolling is stopped by tapping ([@NGB-Was-Taken](https://github.com/NGB-Was-Taken)) ([#2680](https://github.com/mihonapp/mihon/pull/2680))
```
Comment (AntsyLich) [inline CHANGELOG.md:15]:
```suggestion
- Fix reader tap zones triggering after scrolling was stopped by the user ([@NGB-Was-Taken](https://github.com/NGB-Was-Taken)) ([#2680](https://github.com/mihonapp/mihon/pull/2680))
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (NGB-Was-Taken) [reply CHANGELOG.md:15]: I believe that "is stopped" is more correct here than "was stopped". "was stopped" makes it sound like it prevents tap zones from triggering (in the present) if the user has at some point in the past, stopped scrolling.

Also, "by tapping" is more explicit than "by the user" as there are other ways to stop scrolling, like a by drag gesture or a hold gesture.

Comment (AntsyLich) [reply CHANGELOG.md:15]: When are you pushing the other changes

Comment (NGB-Was-Taken) [reply CHANGELOG.md:15]: Was waiting for a response on this to see if you agree or disagree. Will push now.

**Review by AntsyLich — APPROVED** [review]
