### PR TITLE
Mitigate the libraryView NPE crash that occurs for large libraries when removing entries shortly after any other DB write

### LINKED ISSUE #93: Crash when removing items from library
### Steps to reproduce

1. Open tachiyomi.
2. Open any category.
3. Remove multiple items from this category.

### Expected behavior

Nothing happens.

### Actual behavior

Tachiyomi crashes.

### Crash logs

09-19 02:11:20.146 19324 19492 E CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns.
09-19 02:11:20.187 19324 19555 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
09-19 02:11:20.187 19324 19555 E ACRA    : java.lang.NullPointerException
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.CategoriesQueriesImpl$getCategories$1$$ExternalSyntheticOutline0.m(R8$$SyntheticClass:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.MangasQueriesImpl$getLibrary$1.invoke(DatabaseImpl.kt:20)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
09-19 02:11:20.187 19324 19555 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2c9dded, Dispatchers.IO]

### Mihon version

0.16.0

### Android version

Android 14

### Device

Samsung S21 FE

### Other details

https://private-user-images.githubusercontent.com/63903377/189610647-81e213fb-debd-412c-a62b-e5feab33b89f.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTkyMDksIm5iZiI6MTcwNTUxODkwOSwicGF0aCI6Ii82MzkwMzM3Ny8xODk2MTA2NDctODFlMjEzZmItZGViZC00MTJjLWE2MmItZTVmZWFiMzNiODlmLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE5MTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YWY5OWIyMTgyYTZkZWY5OGMzY2MyYzkyN2E5YzNlNzg1MDhhMzdhYjU1ODgxNzJjMWRiYTZiMDIyZjVkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.py8kV9h53gz-iRn6CR0PCW2lTEeD9a0faa7TyPzj50I

The crash still happens in mihon.

~Reference: https://github.com/tachiyomiorg/tachiyomi/issues/7997~
Reference: http://web.archive.org/web/20240130145643/https://git.mihon.dev/tachiyomi/tachiyomi/issues/7997

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FlaminSarge**
Reopening #1794 due to #1799 having the possibility of OOM if the user's DB is astronomically large.
Fixes #93 
Cause is https://github.com/sqldelight/sqldelight/issues/1584 (and https://github.com/sqldelight/sqldelight/issues/4194 )

Similar to the implementation at https://github.com/jobobby04/TachiyomiSY/commit/3a5e23550ff0a1f5be7e03138f63ab4960716f82 and https://github.com/null2264/yokai/commit/50fecd5350c9e4aec04ff76c6849c331ca0d29ed but using 3x retries at 500ms each, 1500ms debounce, and a catch at the end as a "nothing worked but we don't want to crash" state.

Delay values/etc can be tweaked if needed.

### CODE REVIEW

File: domain/src/main/java/tachiyomi/domain/manga/interactor/GetLibraryManga.kt [hunk 1]
```diff
@@ -12,7 +17,20 @@ class GetLibraryManga(
...
+                // retry up to 3x, waiting 500ms between retries
+                (cause is NullPointerException).also {
+                    if (it) delay(500)
+                }
+            }
+            .debounce(1500) // if another update comes in during retries, ditch the retries
+            .catch {
+                // emit nothing during failure
+                // retries didn't work and we don't want to crash
+            }
```
Comment (AntsyLich) [inline domain/src/main/java/tachiyomi/domain/manga/interactor/GetLibraryManga.kt:34]:
```suggestion
            .retry {
                if (it is NullPointerException) {
                    delay(0.5.seconds)
                    true
                } else {
                    false
                }
            }
```

**Review by AntsyLich — CHANGES_REQUESTED** [review]

**Review by AntsyLich — APPROVED** [review]
