### PR TITLE
Use plural forms for update error notification

### LINKED ISSUE #3051: „X update(s) have failed” should use plural forms
### Steps to reproduce

Step 1: Start a library update
Step 2: get an error message: „X update(s) have failed”
Expected behavior

### Expected behavior

String uses plural form, e.g. „1 update have failed”, „2 updates have failed”. This allows proper translation to other languages.

### Actual behavior

Currently the string doesn't use plural form.

### Crash logs

_No response_

### Mihon version

0.19.4

### Android version

Android 16

### Device

Samsung A55

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.19.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Mihon does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

### PR DESCRIPTION
**Pull request by sudo-ezekiel**
Replace the hardcoded "X update(s) failed" string with Android plural resources, enabling proper localization for languages with different plural rules.

Changes

- Added notification_update_error plural entry in base/plurals.xml with one/other quantities
- Updated LibraryUpdateNotifier.kt to use pluralStringResource instead of stringResource
- Marked the old string in base/strings.xml as moved to plurals

Fixes #3051

OLD SINGLE UPDATE ERROR:

OLD_SINGLE_UPDATE

OLD PLURALS UPDATE ERROR:

OLD_UPDATES

NEW SINGLE UPDATE ERROR:

NEW_SINGLE_UPDATE

NEW PLURALS UPDATE ERROR:

NEW_UPDATES

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt [hunk 1]
```diff
@@ -153,7 +153,7 @@ class LibraryUpdateNotifier(
             Notifications.ID_LIBRARY_ERROR,
             Notifications.CHANNEL_LIBRARY_ERROR,
         ) {
-            setContentTitle(context.stringResource(MR.strings.notification_update_error, failed))
+            setContentTitle(context.pluralStringResource(MR.plurals.notification_update_error, failed, failed))
```
Comment (AntsyLich) [inline app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: Pretty sure this will make the app crash on non-english languages. Use a different key for the new string.

File: i18n/src/commonMain/moko-resources/base/strings.xml [hunk 2]
```diff
@@ -922,7 +922,7 @@
     <string name="notification_chapters_single">Chapter %1$s</string>
     <string name="notification_chapters_single_and_more">Chapter %1$s and %2$d more</string>
     <string name="notification_chapters_multiple">Chapters %1$s</string>
-    <string name="notification_update_error">%1$d update(s) failed</string>
+    <!-- notification_update_error moved to plurals.xml -->
```
Comment (AntsyLich) [inline i18n/src/commonMain/moko-resources/base/strings.xml]:
```suggestion
```

File: app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt (hunk 1 above)
Comment (sudo-ezekiel) [reply app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: Applied both changes, removed the comment and renamed the key to notification_update_errors. Worth noting the original name wouldn't have crashed since strings and plurals are separate namespaces (R.string.* vs R.plurals.*), but a distinct key is cleaner.

That being said my experience with Kotlin is next to nothing, so cheers.

Comment (AntsyLich) [reply app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: Oh you're right it wouldn't have crashed the app. Should be fine to revert the key change.

Comment (sudo-ezekiel) [reply app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: You tell me if you want to revert the key change or not, I am fine with both of those solutions.

Comment (AntsyLich) [reply app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: Revert it.

Comment (sudo-ezekiel) [reply app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt]: reverted. glhf
