### PR TITLE
Observe tracker login state instead of fetching once

### LINKED ISSUE #964: Filter by "Tracking" temporarily stuck after signing out of tracker
### Steps to reproduce

1) Be signed into Tracker in Settings
2) Go to Library Page > Filter, and filter using tracker (specific like "AniList" or single like "Tracked")
3) Unlink/sign out of Tracker in Settings
4) Library Page is stuck filtering tracker until app restart or relink of Tracker

### Expected behavior

Should stop filter or give option to stop filtering

(Maybe add a "Clear Filters" button or something)

### Actual behavior

Still filters (with yellow icon) but option to disable is gone (since tracker is gone)

### Crash logs

_No response_

### Mihon version

0.16.5 / r6740

### Android version

Android 14

### Device

Samsung S22 Ultra

### Other details

Mentioned/made aware by NGrav in Discord support channel

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AntsyLich**
Fixes #964

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/data/track/BaseTracker.kt [hunk 1]
```diff
@@ -53,6 +55,14 @@ abstract class BaseTracker(
         get() = getUsername().isNotEmpty() &&
             getPassword().isNotEmpty()
 
+    override val isLoggedInFlow: Flow<Boolean>
+        get() = combine(
```
Comment (Syer10) [inline app/src/main/java/eu/kanade/tachiyomi/data/track/BaseTracker.kt:59]: Instead of using a `get()`, just save it to the val instead. This is a cold flow so it wont matter much. Plus saving it might be for better compose since it wont accidentally re-collect on run.

**Review by Syer10 — APPROVED** [review]
